### PR TITLE
Fix LaserScan metadata

### LINKED ISSUE #4: scan_time and time_increment are 0
**Describe the bug**
Looking at the content of the message published on the topic /scan, the values scan_time and time_increment are 0

**To Reproduce**
1. Run `ros2 launch pf_driver r2000.launch.py`
2. Run `ros2 topic echo /scan`
3. See values:
`time_increment: 0.0
scan_time: 0.0
`

**Expected behavior**
These two values should represent the time between two points readings, and the total time of 360° reading.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - ROS Version: ROS2 humble

**Sensor**
 - Device:  R2000 UHD
 - FW Version: 1.61
 - HW Version: 1.73

### PR DESCRIPTION
**Pull request by kawk**
Some metadata in the `LaserScan` messages seems to be inconsistent with the `msg/LaserScan` specification or not set at all.

These changes try to improve the content of the fields `scan_time`, `angle_min`, `angle_max`, `angle_increment` and `time_increment`.  A more detailed description of the changes is included in `docs/metadata.md` (which might be a bit too much about internals to be included as is?)

Note that especially the changes to the angle information might not match expectations of existing subscriber implementations, while `scan_time` and `time_increment` weren't usable before anyway - as a side effect this probably fixes #4 

The changes additionally try to avoid deduction of the metadata from static driver configuration. Instead, as much as possible information is gathered from the received packet header.

### CODE REVIEW

File: src/pf_driver/src/pf/r2300/pfsdp_2300.cpp [hunk 1]
```diff
@@ -18,61 +18,13 @@ PFSDP_2300::PFSDP_2300(std::shared_ptr<rclcpp::Node> node, std::shared_ptr<Handl
...
-  // float min = (measure_start_angle > start_angle) ? measure_start_angle : start_angle;
-  // float max = measure_stop_angle;
-  return std::pair<float, float>(measure_start_angle, measure_stop_angle);
-}
-
-std::string PFSDP_2300::get_start_angle_str()
-{
-  return std::string("start_angle");
+  params_->sampling_rate_max = parser_utils::to_long(resp["sampling_rate_max"]);
+  params_->scan_time_factor = 1;
```
Comment (JnsHndr) [inline src/pf_driver/src/pf/r2300/pfsdp_2300.cpp]: I think that the value layer_count read from the device (R2300) should be assigned here.
params_->scan_time_factor = parser_utils::to_long(resp["layer_count"]);

If a R2300-4-layer (device_family==5) is connected, then params_->scan_time_factor = num_layers is first set to 4 which comes from config/r2300_params.yaml (call stack: main() ---> pf_interface.init()/PFInterface::init() ---> PFInterface::handle_version()) and later overwritten with params_->scan_time_factor = 1 (call stack: main() ---> pf_interface.init()/PFInterface::init() ---> protocol_interface_->update_scanoutput_config() ---> PFSDP_2300::get_scan_parameters()).

Comment (kawk) [reply src/pf_driver/src/pf/r2300/pfsdp_2300.cpp]: The `scan_time_factor` depends on whether there are separate `LaserScan` topics for each layer (R2300 4-layer). The current driver emits separate topics for R2300 4-layer but not R2300 1-layer, although both report `layer_count=4`. It probably should become a user option to choose separate or unified output for R2300 1-layer

Comment (kawk) [reply src/pf_driver/src/pf/r2300/pfsdp_2300.cpp]: In 9b97265 the `scan_time_factor` setting is done only once near PacketReader instantiation, to avoid later overwrite. 

The purpose of `num_layers` YAML parameter is unclear to me. Until now it just seems to be expected to replicate the actual number of layers in sensor (which can be read from sensor as `layer_count` parameter).
